# Generated by Django 3.0 on 2020-03-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=200)),
                ('a_email', models.CharField(max_length=200)),
                ('a_password', models.CharField(max_length=200)),
            ],
        ),
    ]
