# Generated by Django 3.0 on 2020-03-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_email', models.CharField(max_length=200)),
                ('teacher_password', models.CharField(max_length=200)),
                ('teacher_qualification', models.CharField(max_length=200)),
            ],
        ),
    ]
