# Generated by Django 3.0 on 2020-03-06 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newteacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_email', models.CharField(max_length=200)),
                ('teacher_password', models.CharField(max_length=200)),
                ('teacher_qualification', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Admin')),
            ],
        ),
    ]
