# Generated by Django 3.0 on 2020-03-06 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_newteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newteacher',
            name='admin',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.DeleteModel(
            name='Newteacher',
        ),
    ]
