# Generated by Django 3.0 on 2020-03-06 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Admin')),
            ],
        ),
    ]
