# Generated by Django 3.0 on 2020-03-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
